#!/bin/bash

LIB=${0/%KurogoShell/}
APP=`pwd`
phpPath=`which php`

if [ -n "$phpPath" ]; then
    ${phpPath} -q ${LIB}KurogoShellDispatcher.php -working "${APP}" "$@"
    return=$?
    if [ ${return} -gt 0 ]; then
        if [ ${return} -eq 1 ]; then
            echo "Command not specified"
        elif [ ${return} -eq 2 ]; then
            echo "Module Disabled"
        elif [ ${return} -eq 3 ]; then
            echo "Unauthorized"
        elif [ ${return} -eq 4 ]; then
            echo "Module '$1' does not understand command '$2'"
        elif [ ${return} -eq 5 ]; then
            echo "Module $1 not found"
        elif [ ${return} -eq 6 ]; then
            echo "Unable to load Kurogo class"
        elif [ ${return} -eq 7 ]; then
            echo "Usage: KurogoShell module command"
        else
            echo "Code:${return}"
        fi
    fi
else
    echo "PHP binary not found in path"
fi

exit ${return}
